version: "2"

services:
  cloudcode:
    build:
      context: .
      args:
        - registry_url
    env_file: .env
    environment:
      PORT: 8085
    image: poddworks/lambda-parse-cloudcode:1.4.0
    ports:
      - "8085:8085"
    networks:
      - backend

networks:
  backend:
